use crate::cli::GenerateAction;
use crate::client::GrafanaClient;
use crate::commands::cache;
use crate::commands::panel::{
    build_var_map, expand_vars, extract_panels, parse_panel, resolve_ds_uid,
};
use crate::config::ResolvedConfig;
use crate::error::{GrafanaError, Result};
use crate::render::{chart, shell};
use owo_colors::OwoColorize;

pub async fn run(cfg: &ResolvedConfig, action: &GenerateAction) -> Result<()> {
    match action {
        GenerateAction::Metric { uid, panel } => metric(cfg, uid, *panel).await,
        GenerateAction::Chart {
            uid,
            panel,
            range,
            step,
        } => chart_cmd(cfg, uid, *panel, *range, *step).await,
        GenerateAction::Dashboard { uid } => dashboard(cfg, uid).await,
    }
}

async fn metric(cfg: &ResolvedConfig, uid: &str, panel_id: i64) -> Result<()> {
    let client = GrafanaClient::new(cfg)?;
    let env = client.get_dashboard(uid).await?;
    let panels = extract_panels(&env.dashboard);
    let panel = panels
        .iter()
        .find(|p| p.get("id").and_then(|v| v.as_i64()) == Some(panel_id))
        .ok_or(GrafanaError::PanelNotFound(panel_id))?;
    let info = parse_panel(panel);

    println!("# Panel {}: {}", info.id, info.title);
    println!("# type: {}", info.ptype);
    if let Some(ds) = &info.ds_uid {
        println!("# datasource uid: {ds}");
    }
    if let Some(ds) = &info.ds_type {
        println!("# datasource type: {ds}");
    }
    if info.targets.is_empty() {
        println!("# (no query targets)");
    }
    for (i, t) in info.targets.iter().enumerate() {
        println!("\n# query [{i}]");
        println!("{}", t.expr);
    }
    Ok(())
}

async fn chart_cmd(
    cfg: &ResolvedConfig,
    uid: &str,
    panel_id: i64,
    range: i64,
    step: i64,
) -> Result<()> {
    let client = GrafanaClient::new(cfg)?;
    let env = client.get_dashboard(uid).await?;
    let panels = extract_panels(&env.dashboard);
    let panel = panels
        .iter()
        .find(|p| p.get("id").and_then(|v| v.as_i64()) == Some(panel_id))
        .ok_or(GrafanaError::PanelNotFound(panel_id))?;
    let info = parse_panel(panel);

    let vars = build_var_map(&env.dashboard);
    let cache_map = cache::load(&cfg.profile_name)?;

    let raw_ds = info
        .ds_uid
        .clone()
        .or_else(|| info.targets.iter().find_map(|t| t.ds_uid.clone()))
        .unwrap_or_else(|| "$datasource".to_string());
    let ds_uid = resolve_ds_uid(&raw_ds, &vars, cache_map.as_ref()).ok_or_else(|| {
        GrafanaError::UnsupportedDatasource(format!("cannot resolve datasource '{raw_ds}'"))
    })?;

    let ds_kind = cache_map
        .as_ref()
        .and_then(|m| m.datasources.get(&ds_uid))
        .map(|d| d.kind.clone())
        .or_else(|| info.ds_type.clone())
        .unwrap_or_else(|| "prometheus".to_string());
    if ds_kind != "prometheus" {
        return Err(GrafanaError::UnsupportedDatasource(ds_kind));
    }

    let raw_expr = info
        .targets
        .first()
        .map(|t| t.expr.clone())
        .ok_or_else(|| GrafanaError::UnsupportedDatasource("no targets".into()))?;
    let expr = expand_vars(&raw_expr, &vars);

    println!(
        "{} {} (panel {})",
        "Querying".cyan(),
        info.title.bold(),
        info.id
    );
    println!("  datasource: {ds_uid}");
    println!("  expr: {expr}");
    if expr != raw_expr {
        println!("  (raw): {raw_expr}");
    }
    println!("  range: {range}s, step: {step}s");

    let resp = client
        .ds_query_prometheus(&ds_uid, &expr, range, step)
        .await?;
    let series = chart::extract_series(&resp);
    println!("\n{}", chart::render_ascii(&series, 100, 24));
    Ok(())
}

async fn dashboard(cfg: &ResolvedConfig, uid: &str) -> Result<()> {
    let client = GrafanaClient::new(cfg)?;
    let env = client.get_dashboard(uid).await?;
    let dash = &env.dashboard;
    let title = dash.get("title").and_then(|v| v.as_str()).unwrap_or("?");
    let cache_map = cache::load(&cfg.profile_name)?;
    let vars = build_var_map(dash);

    println!("#!/usr/bin/env bash");
    println!("# Generated by grafana-cli — reproduction script for dashboard");
    println!("# Title: {title}");
    println!("# UID:   {uid}");
    println!("set -euo pipefail\n");

    for p in extract_panels(dash) {
        let info = parse_panel(p);
        if info.targets.is_empty() {
            continue;
        }
        println!("# ── Panel {}: {} ({})", info.id, info.title, info.ptype);
        let raw_ds = info
            .ds_uid
            .clone()
            .or_else(|| info.targets.iter().find_map(|t| t.ds_uid.clone()))
            .unwrap_or_default();
        let ds_uid = resolve_ds_uid(&raw_ds, &vars, cache_map.as_ref());
        let ds_kind = ds_uid
            .as_ref()
            .and_then(|uid| cache_map.as_ref().and_then(|m| m.datasources.get(uid)))
            .map(|d| d.kind.as_str())
            .or(info.ds_type.as_deref())
            .unwrap_or("prometheus");
        let ds_url = ds_uid
            .as_ref()
            .and_then(|uid| cache_map.as_ref().and_then(|m| m.datasources.get(uid)))
            .and_then(|d| d.url.clone())
            .unwrap_or_else(|| "http://localhost:9090".to_string());

        for (i, t) in info.targets.iter().enumerate() {
            let expr = expand_vars(&t.expr, &vars);
            println!("# query [{i}]: {expr}");
            match ds_kind {
                "prometheus" => println!("{}", shell::curl_prometheus_instant(&ds_url, &expr)),
                "loki" => println!("{}", shell::logcli_query(&expr)),
                other => println!("# unsupported datasource: {other}"),
            }
        }
        println!();
    }
    Ok(())
}
